# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  #joint_a1: -1.45
  #joint_a2: -0.66
  #joint_a3: -0.75
  #joint_a4: -1.3962
  #joint_a5: 0.65
  #joint_a6: 1.7109
  #joint_a7: 0.0
  
  joint_a1: 1.2
  joint_a2: 1.6
  joint_a3: 1.4
  joint_a4: 1.4
  joint_a5: -0.5
  joint_a6: 0.011
  joint_a7: 2.4
