# Default initial positions for the panda arm's ros2_control fake system
initial_positions:
  joint_a1: -1.45
  joint_a2: -0.66
  joint_a3: -0.75
  joint_a4: -1.3962
  joint_a5: 0.35
  joint_a6: 1.6
  joint_a7: 0.0
  

